# Uncomment the next line to define a global platform for your project
 platform :ios, '15.5'
inhibit_all_warnings!

target 'JiTingPlayerOC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'ReactiveObjC', '3.1.1'
  pod 'AFNetworking', '~> 4.0.1'
  pod 'Masonry', '1.1.0'
  pod 'PINCache', '~> 3.0.3'
  
  post_install do |installer|
    installer.pods_project.build_settings('Debug')['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    installer.pods_project.build_settings('Debug')['EXCLUDED_ARCHS[sdk=*]'] = 'armv7'
    installer.pods_project.build_settings('Release')['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    installer.pods_project.build_settings('Release')['EXCLUDED_ARCHS[sdk=*]'] = 'armv7'
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
        config.build_settings['ENABLE_BITCODE'] = 'YES'
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        config.build_settings['CLANG_WARN_UNGUARDED_AVAILABILITY'] = 'NO'
        config.build_settings['CLANG_WARN_STRICT_PROTOTYPES'] = 'NO'
        config.build_settings['CLANG_WARN_OBJC_LITERAL_CONVERSION'] = 'YES_ERROR'
        config.build_settings['GCC_WARN_UNDECLARED_SELECTOR'] = 'NO'
        config.build_settings['CLANG_WARN_NON_LITERAL_NULL_CONVERSION'] = 'YES_ERROR'
        config.build_settings['GCC_TREAT_INCOMPATIBLE_POINTER_TYPE_WARNINGS_AS_ERRORS'] = 'YES'
        config.build_settings['OTHER_CFLAGS'] ||= []
        config.build_settings['OTHER_CFLAGS'] << '-Werror=unguarded-availability-new -Werror=unknown-warning-option -Werror=sometimes-uninitialized -Werror=objc-protocol-method-implementation -Werror=macro-redefined -Werror=objc-designated-initializers -Werror=unused-getter-return-value -Werror=incomplete-implementation -Wno-arc-performSelector-leaks -Werror=property-attribute-mismatch -Wnullability-completeness -Werror=protocol -Werror=objc-missing-super-calls -Werror=nonnull -Wno-nullability-completeness -Werror=incompatible-pointer-types -Wno-deprecated-declarations'
        config.build_settings['OTHER_CFLAGS'] << '-Wno-format'
      end
    end
  end
end
